### ISSUE TITLE
Support audio playback in stories

### ISSUE THREAD

**Issue by newmuis** [newmuis/amphtml-story#146]
- [x] Allow playing story-level audio (implemented in #125)
- [x] Allow playing page-level audio (implemented in #92)
- [x] Allow managing audio from embedded media elements (implemented in #111)
- [x] Automatically lower volume of background audio when other sources are playing (implemented in #121)
- [x] Allow muting/unmuting audio with UI control (implemented in #101)
- [x] Indicate whether audio is playing with UI control (implemented in #126)
- [ ] Crossfade audio when increasing/decreasing volumes
- [ ] Crossfade audio when stopping/playing audio sources
- [ ] Allow playing audio after auto-advancement
- [ ] Allow managing audio of ad experiences
- [x] Preload audio when page is preloaded (implemented in #125)

**Comment by newmuis** [comment]
Crossfading and ad support are features (which aren't tracked here); I will file a new bug regarding audio playback with auto-advancement upstream.
