### ISSUE TITLE
Improve video performance in stories

### ISSUE THREAD

**Issue by newmuis** [newmuis/amphtml-story#147]
- [x] Preload videos when page is preloaded (implemented in #98)
- [x] Pause videos when page is paused (implemented in #112)
- [x] Resume videos when page is resumed (implemented in #112)
- [x] Allow adaptive bitrate streaming of videos (see [amphtml #7744](https://github.com/ampproject/amphtml/issues/7744))
- [ ] Allow caching of videos
- [x] Wait for videos' `canplay` or `canplaythrough` event
- [x] Require poster images of videos

**Comment by newmuis** [comment]
All items here are complete except for caching, which is tracked separately by the AMP cache folks.
